version: '3'
name: 'wormhole-devcontainer'
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: wormhole.dev-environment
        container_name: wormhole.dev-environment
        volumes:
            - ..:/workspace
            - node_modules:/workspace/node_modules
        command:
            - sleep
            - infinity
            - bash
        init: true
volumes:
    node_modules:
