name: CI

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Use Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: '21.5.0'

            - name: Install yarn
              run: npm install -g yarn

            - name: Check and fix duplicates
              run: yarn deduplicate && git diff --exit-code

            - name: Install Dependencies
              run: yarn install --frozen-lockfile

            - name: Run lint
              run: yarn lint
